// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 11.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4.Generator.Basic
{
    using System.Linq;
    using System.Text;
    using System.Xml;
    using System.IO;
    using System.Globalization;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class Generator : GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.ComponentModel.Dat" +
                    "aAnnotations.Schema;\r\nusing System.Globalization;\r\nusing System.Runtime.Serializ" +
                    "ation;\r\n\r\nnamespace ");
            
            #line 14 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(" {\r\n\r\n/// <summary>\r\n/// Automatically generated from\r\n/// ");
            
            #line 18 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.FilePath));
            
            #line default
            #line hidden
            this.Write("\r\n/// </summary>\r\n[DataContract, Serializable]\r\npublic class ");
            
            #line 21 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(@" {

    private string _Identifier;

    [DataMember]
    public string Name { get; private set; }

    [DataMember]
    public string Description { get; private set; }

    [DataMember]
    public DateTime StartDate { get; private set; }

    [DataMember]
    public DateTime EndDate { get; private set; }

    [DataMember]
    public string Identifier 
    { 
        get
        {
            return _Identifier;
        }
        set
        {
            if (_Identifier != value) {
                _Identifier = value;
                SetProperties(this);
            }
        }
    }

    public ");
            
            #line 53 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(string identifier) \r\n    {\r\n        Identifier = identifier;\r\n    }\r\n\r\n    publi" +
                    "c ");
            
            #line 58 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("() { }\r\n\r\n    public static implicit operator ");
            
            #line 60 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(string identifier) \r\n    {\r\n        return new ");
            
            #line 62 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(identifier);\r\n    }\r\n\r\n    public static implicit operator string(");
            
            #line 65 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" item) \r\n    {\r\n        return item != null ? item.Identifier : null;\r\n    }\r\n\r\n " +
                    "   public override string ToString()\r\n    {\r\n        return Identifier;\r\n    }\r\n" +
                    "\r\n");
            
            #line 75 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"

    foreach(var item in Model) {

            
            #line default
            #line hidden
            this.Write("    /// <summary>\r\n    /// ");
            
            #line 79 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Identifier));
            
            #line default
            #line hidden
            this.Write(" - ");
            
            #line 79 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    /// </summary>\r\n    [NotMapped]\r\n    public static readonly ");
            
            #line 82 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 82 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.FieldName));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 82 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("(\"");
            
            #line 82 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Identifier));
            
            #line default
            #line hidden
            this.Write("\");\r\n\r\n");
            
            #line 84 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"

    } // for loop

            
            #line default
            #line hidden
            this.Write("\r\n    [NotMapped]\r\n    public static readonly IEnumerable<");
            
            #line 89 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("> AllCodes = new ");
            
            #line 89 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("[]\r\n    { \r\n        ");
            
            #line 91 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(String.Join(",", Model.Select(x => x.FieldName))));
            
            #line default
            #line hidden
            this.Write(" \r\n    };\r\n\r\n    [NotMapped]\r\n    public static IEnumerable<");
            
            #line 95 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write("> AllActiveCodes\r\n    {\r\n        get\r\n        {\r\n            return AllCodes.Wher" +
                    "e(x => x.StartDate <= DateTime.Today && x.EndDate >= DateTime.Today);\r\n        }" +
                    "\r\n    }\r\n\r\n    private static void SetProperties(");
            
            #line 103 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ClassName));
            
            #line default
            #line hidden
            this.Write(" obj) \r\n    {\r\n        switch (obj.Identifier) {\r\n");
            
            #line 106 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"

            foreach(var item in Model) {

            
            #line default
            #line hidden
            this.Write("                case @\"");
            
            #line 109 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Identifier));
            
            #line default
            #line hidden
            this.Write("\": \r\n                    obj.Name = @\"");
            
            #line 110 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n                    obj.Description = @\"");
            
            #line 111 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Description));
            
            #line default
            #line hidden
            this.Write("\";\r\n                    obj.StartDate = DateTime.ParseExact(@\"");
            
            #line 112 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Startdate));
            
            #line default
            #line hidden
            this.Write("\", @\"");
            
            #line 112 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTimeFormatString));
            
            #line default
            #line hidden
            this.Write("\", CultureInfo.InvariantCulture);\r\n                    obj.EndDate = DateTime.Par" +
                    "seExact(@\"");
            
            #line 113 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Enddate));
            
            #line default
            #line hidden
            this.Write("\", @\"");
            
            #line 113 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(DateTimeFormatString));
            
            #line default
            #line hidden
            this.Write("\", CultureInfo.InvariantCulture);\r\n                    break;\r\n");
            
            #line 115 "C:\Users\z8zse\Documents\GitHub\t4-template-tests\CodeList.Generator\Basic\Generator.tt"

            }

            
            #line default
            #line hidden
            this.Write("                default: \r\n                    break;\r\n        }\r\n    }\r\n\r\n\r\n} //" +
                    " class\r\n} // namespace");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class GeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
