language: csharp
solution: t4-template-tests.sln
install:
  - nuget restore t4-template-tests.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release t4-template-tests.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./T4.Test/bin/Release/T4.Test.dll
